### ISSUE TITLE
Provide auto registration of gRPC client beans

### ISSUE THREAD

**Issue by DanielLiu1123** [spring-projects-experimental/spring-grpc#91]
As mentioned in [this comment](https://github.com/spring-projects-experimental/spring-grpc/issues/87#issuecomment-2571516478), users still need to manually register client beans:
```java
@Bean
SimpleGrpc.SimpleBlockingStub stub(GrpcChannelFactory channels) {
    return SimpleGrpc.newBlockingStub(channels.createChannel("local").build());
}
```

In real-world applications, a service might use dozens or even hundreds of gRPC clients (I’m working on such a project). Manually registering gRPC client beans is unsatisfactory, especially when considering migrating starters from other community implementations to `spring-grpc`.

Similar issues occur with [HTTP interfaces](https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-http-interface). We can look at [this issue](https://github.com/spring-projects/spring-framework/issues/33992) and how they plan to solve it. The same pattern should work for gRPC clients.

Here is a feasible solution I propose, [grpc-starter](https://danielliu1123.github.io/grpc-starter/docs/client/autoconfiguration) provides a fully configuration-driven approach:
```yaml
grpc:
  client:
    base-packages: [ com.example ]
    channels:
      - authority: user-service:9090
        stubs: # All clients under this configuration share this channel
          - com.example.user.v1.** # Ant-style patterns
          - com.example.user.v2.**
      - authority: order-service:9090
        stubs:
          - com.example.order.**
```
Then you can inject gRPC client beans into any Spring beans. I hope `spring-grpc` can provide a similar solution.
